[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Variables Supabase
  VITE_SUPABASE_URL = "https://xtjzuqyvyzkzchwtjpeo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0anp1cXl2eXpremNod3RqcGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mzk0OTUsImV4cCI6MjA2NzMxNTQ5NX0.MTSeZGl2JnmoB8c5B7GQ2iKnHm3CFip0nn1jtmSOAIA"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
